# action.yml
name: 'Terraform security scan'
description: 'Scan your terraform code with tfsec'
inputs:
  tfsec_actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
  tfsec_actions_working_dir:
    description: 'Terraform working directory.'
    default: '.'
runs:
  using: 'docker'
  image: './Dockerfile'
